In [1]:
import pandas as pd

In [2]:
df = pd.read_csv ('questionnaire data/user_profiles_lupa.csv')

In [12]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [14]:
df.columns

Index(['id', 'user_id', 'gender', 'birth_date', 'national_id', 'patient_id', 'postal_code', 'address', 'colonia', 'weight', 'height', 'weight_type', 'height_type', 'intervened', 'intervened_when', 'disabled', 'notifications', 'notifications_time_type', 'admin_id', 'admin_user_id', 'home_type_id', 'employment_type_id', 'living_type_id', 'govt_confined_type', 'selected_language_id', 'created_at', 'updated_at', 'insurance_id', 'questionnaire_reminder_time', 'is_questionnaire_reminder_notification', 'is_mwb_reminder_notification', 'mwb_reminder_time', 'is_allowed_analytical_cookies', 'is_allowed_personalization_cookies', 'is_caregiver', 'is_onboarding_finished', 'city_id', 'country_id', 'mwb_on_boarding_shown', 'corona_answers_sum', 'children', 'marital_status_id', 'partner', 'smoke', 'weekly_physical_activity_id', 'religious', 'ethnicity_id', 'employment_status_id', 'household_income_id', 'educational_level_id', 'children_gender'], dtype='object')

In [16]:
df["datetime"] = pd.to_datetime(df["created_at"])

In [17]:
df["datetime_up"] = pd.to_datetime(df["updated_at"])

In [21]:
y = df["datetime_up"] - df["datetime"]

In [38]:
df['segundos_activo'] = y.dt.seconds

AttributeError: 'TimedeltaProperties' object has no attribute 'minute'

In [39]:
segundos_activos = df[['user_id', 'segundos_activo']]

In [40]:
segundos_activos.to_csv('segundos_activos.csv')

In [42]:
df = pd.read_csv ('questionnaire data/users_lupa.csv')

In [43]:
df

    id  first_name  last_name          email    email_verified_at  phone_prefix  phone_number  phone_verified_at                                           password  is_anonymous  is_terms_conditions           deleted_at  remember_token           created_at           updated_at  password_updated_at  is_stars_user  third_party_user_id      time_zone  is_personalization_accepted  force_ignore_questionnaire_frequency  third_party_username            banned_at
0  113         NaN        NaN  L001@lupa.com  2021-01-12 15:59:23           NaN           NaN                NaN  $2y$10$KHsiouEQztMykPF.pP5fbuB7LNcaRwGGAueTDAa...          True                 True                  NaN             NaN  2021-01-12 15:59:23  2021-05-20 13:02:23  2021-04-20 11:45:23          False                  NaN  Europe/Madrid                        False                                 False                   NaN  2021-05-20 13:02:23
1  121         NaN        NaN  L009@lupa.com  2021-01-12 15:59:24           NaN           NaN                NaN  $2y$10$Rxgcjmn2gHiKurCGL6HkAe4pI79OqK4Oq2h/Uq4...          True                 True                  NaN             NaN  2021-01-12 15:59:24  2021-05-20 13:02:55  2021-03-15 09:26:51          False                  NaN  Europe/Madrid                        False                                 False                   NaN  2021-05-20 13:02:55
2  122         NaN        NaN  L010@lupa.com  2021-01-12 15:59:24           NaN           NaN                NaN  $2y$10$LBAh/zwQalCRej4YsXGDV.2EGZxfPVG7XzR9izx...          True                 True  2021-03-15 16:49:51             NaN  2021-01-12 15:59:24  2021-02-18 12:31:29  2021-02-18 12:31:29          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
3  123         NaN        NaN  L011@lupa.com  2021-01-12 15:59:24           NaN           NaN                NaN  $2y$10$WkFE04Yi0WkS/nI7QDmsmOUFjkne2LgO7Hj.PVJ...          True                 True                  NaN             NaN  2021-01-12 15:59:24  2021-06-07 15:52:29  2021-05-17 08:38:53          False                  NaN  Europe/Madrid                        False                                 False                   NaN  2021-06-07 15:52:29
4  125         NaN        NaN  L013@lupa.com  2021-01-12 15:59:24           NaN           NaN                NaN  $2y$10$7CgCExlDMMpoOGxwx3Afg.KnKd9su5ZDT6iqQjC...          True                 True                  NaN             NaN  2021-01-12 15:59:24  2021-05-20 10:22:52  2021-05-20 10:22:52          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
5  126         NaN        NaN  L014@lupa.com  2021-01-12 15:59:25           NaN           NaN                NaN  $2y$10$5gYdmZ47hk2FCcAZXgx7bOW5XGhsOqLkHntGmjl...          True                 True                  NaN             NaN  2021-01-12 15:59:25  2021-05-14 08:14:27  2021-05-14 08:14:27          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
6  127         NaN        NaN  L015@lupa.com  2021-01-12 15:59:25           NaN           NaN                NaN  $2y$10$7IMKiwusRgA1WVraSXfeeO50lDg0uuLjR/SbDgO...          True                 True                  NaN             NaN  2021-01-12 15:59:25  2021-05-25 09:48:30  2021-05-25 09:48:30          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
7  128         NaN        NaN  L016@lupa.com  2021-01-12 15:59:25           NaN           NaN                NaN  $2y$10$djYjj4TfX8PsTRi9p5pAQea/H18IWTs9eEJTA/d...          True                 True                  NaN             NaN  2021-01-12 15:59:25  2021-05-14 08:37:24  2021-05-14 08:37:24          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
8  173         NaN        NaN  L017@lupa.com  2021-03-31 05:15:23           NaN           NaN                NaN  $2y$10$/nbQMt76mA2KFlB.z.OZuunZX.TCP0yxcPoJ256...          True                 True                  NaN             NaN  2021-03-31 05:15:23  2021-05-28 09:06:55  2021-05-28 09:06:55          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN
9  174         NaN        NaN  L018@lupa.com  2021-03-31 05:15:23           NaN           NaN                NaN  $2y$10$NF9MKES77YAperT8f1bg6eXKGOSuIGdXz2oTI8w...          True                 True                  NaN             NaN  2021-03-31 05:15:23  2021-05-20 12:53:59  2021-05-20 12:53:59          False                  NaN  Europe/Madrid                        False                                 False                   NaN                  NaN